# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e1e3203c99e63a4a103c2da2bd5a336889514e50e9aaf4eee1d0cbbff2ab60d6d3c98fa97e53196e1df0325c5dd934ef8b171bc181aaf3fbc7cb3d49c245e1d

test:
  secret_key_base: 00e5e26f88183ae48f365ede9f146650e502ea46d50e9d56091e1c96dc29531882606ccc1a795f191b2aa01f0bc32b65f219594473ac851dcc322acf38150c78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
